FROM cppnow17_nbdl_build:emscripten

RUN npm install -g http-server

  WORKDIR /opt/build
  CMD cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_TOOLCHAIN_FILE='/opt/toolchain.cmake' \
    /opt/src \
    && /bin/bash
