FROM ricejasonf/emscripten
WORKDIR /usr/local/src

RUN apt-get -yq update && apt-get install -yq vim
RUN npm install -g http-server

# Boost.Hana (workaround branch)
RUN git clone -b bugfix/constexpr_arrays https://github.com/ricejasonf/hana.git \
  && cp -r hana/include/* /usr/local/src/emscripten/system/include \
  && rm -rf hana

# Kvasir.Mpl
RUN git clone -b development https://github.com/kvasir-io/mpl.git \
  && cd mpl && git checkout 41c85408d7777b6d476fe70cd6cfcaad8f02a19c && cd .. \
  && cp -r mpl/src/* /usr/local/include \
  && cp -r mpl/src/* /usr/local/src/emscripten/system/include \
  && rm -rf mpl

# Nbdl
RUN git clone -b cppnow17 https://github.com/ricejasonf/nbdl.git \
  && cp -r nbdl/include/* /usr/local/src/emscripten/system/include \
  && rm -rf nbdl

# Debug just doesn't work with emscripten right now
ARG BUILD_TYPE=Release
ENV BUILD_TYPE ${BUILD_TYPE}

EXPOSE 8080
WORKDIR /opt/build
CMD /usr/local/src/emscripten/emconfigure cmake \
  -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
  /opt/src \
  && echo '. /usr/share/bash-completion/bash_completion && set -o vi' >> /root/.bashrc \
  && /bin/bash
