FROM ricejasonf/emscripten
WORKDIR /usr/local/src

RUN apt-get update \
  && apt-get install -yq ruby vim \
  && npm install http-server -g

RUN git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim \
  &&  echo 'set nocompatible' > ~/.vimrc \
  &&  echo 'filetype off' >> ~/.vimrc \
  &&  echo 'set rtp+=~/.vim/bundle/Vundle.vim' >> ~/.vimrc \
  &&  echo 'call vundle#begin()' >> ~/.vimrc \
  &&  echo "Plugin 'VundleVim/Vundle.vim'" >> ~/.vimrc \
  &&  echo "Plugin 'octol/vim-cpp-enhanced-highlight'" >> ~/.vimrc \
  &&  echo 'call vundle#end()' >> ~/.vimrc \
  &&  echo 'filetype plugin indent on' >> ~/.vimrc \
  &&  echo 'set hlsearch' >> ~/.vimrc \
  && vim +PluginInstall +qall

# Metabench
RUN curl -o \
  /opt/metabench.cmake \
  https://raw.githubusercontent.com/ldionne/metabench/master/metabench.cmake

# Boost.Hana (clang c++1z workaround branch)
RUN git clone -b bugfix/constexpr_arrays https://github.com/ricejasonf/hana.git \
  && cp -r hana/include/* /usr/local/include \
  && rm -rf hana

# Nbdl
RUN git clone https://github.com/ricejasonf/nbdl.git \
  && cp -r nbdl/include/* /usr/local/include \
  && rm -rf nbdl

ARG BUILD_TYPE=Debug
ENV BUILD_TYPE ${BUILD_TYPE}

ARG PORT=8080
ENV PORT ${PORT}
EXPOSE ${PORT}

WORKDIR /opt/build
CMD cmake \
  -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
  -DCMAKE_CXX_FLAGS=" -stdlib=libc++ -DASIO_STANDALONE -DASIO_NO_TYPEID" \
  -DCMAKE_EXE_LINKER_FLAGS=" -lc++abi" \
  /opt/src \
  && echo '. /usr/share/bash-completion/bash_completion && set -o vi' >> /root/.bashrc \
  && /bin/bash
