...
# Boost.Hana (c++1z workaround branch)
RUN git clone -b bugfix/constexpr_arrays \
      https://github.com/ricejasonf/hana.git \
  && cp -r hana/include/* /usr/local/src/emscripten/system/include \
  && rm -rf hana

# Kvasir.Mpl
RUN git clone -b development \
      https://github.com/kvasir-io/mpl.git \
  && cp -r mpl/src/* /usr/local/include \
  && cp -r mpl/src/* /usr/local/src/emscripten/system/include \
  && rm -rf mpl

# Nbdl
RUN git clone -b cppnow17 \
      https://github.com/ricejasonf/nbdl.git \
  && cp -r nbdl/include/* /usr/local/src/emscripten/system/include \
  && rm -rf nbdl
...
